Browser("HPE Service Manager: Login_2").Page("HPE Service Manager: Login").WebEdit("Username").Set "Leader2" @@ hightlight id_;_Browser("HPE Service Manager: Login 2").Page("HPE Service Manager: Login").WebEdit("Username")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("HPE Service Manager: Login_2").Page("HPE Service Manager: Login").WebEdit("Password").SetSecure "5b3af5179f423472f1a2404d83235e3b75281e10196c" @@ hightlight id_;_Browser("HPE Service Manager: Login 2").Page("HPE Service Manager: Login").WebEdit("Password")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("HPE Service Manager: Login_2").Page("HPE Service Manager: Login").WebButton("Log In").Click @@ hightlight id_;_Browser("HPE Service Manager: Login 2").Page("HPE Service Manager: Login").WebButton("Log In")_;_script infofile_;_ZIP::ssf20.xml_;_

Browser("HPE Service Manager").Page("HPE Service Manager").WebElement("ext-gen-top124").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").WebElement("ext-gen-top124")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Link("Hỗ Trợ Xử Lý Các Yêu Cầu").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Link("Hỗ Trợ Xử Lý Các Yêu Cầu")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Link("Tạo Mới Yêu Cầu").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Link("Tạo Mới Yêu Cầu")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").Image("fill").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").Image("fill")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("popupFrame").Link("LEADER2").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("popupFrame").Link("LEADER2")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").Image("fill_2").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").Image("fill 2")_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("popupFrame").Link("NV7").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("popupFrame").Link("NV7")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/vcb.phonedv").Set "0987654321" @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/vcb.phonedv")_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/title").Set "test abc" @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/title")_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebElement("X28View").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebElement("X28View")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/description/descripti").Set "test 123" @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebEdit("instance/description/descripti")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebButton("Gửi Yêu Cầu").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-580247").WebButton("Gửi Yêu Cầu")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Sync @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("HPE Service Manager").CloseAllTabs

