Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebEdit("Username").Set "Leader2" @@ hightlight id_;_Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebEdit("Username")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebEdit("Password").SetSecure "5b39db4bb4b225925114c5dfd9751aacd937015a55f0" @@ hightlight id_;_Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebEdit("Password")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebButton("Log In").Click @@ hightlight id_;_Browser("HPE Service Manager: Login").Page("HPE Service Manager: Login").WebButton("Log In")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").WebElement("ext-gen-top119").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").WebElement("ext-gen-top119")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Link("Hỗ Trợ Xử Lý Các Yêu Cầu").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Link("Hỗ Trợ Xử Lý Các Yêu Cầu")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Link("Các Yêu Cầu Đang Xử Lý").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Link("Các Yêu Cầu Đang Xử Lý")_;_script infofile_;_ZIP::ssf6.xml_;_
'Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-86752").Link("S180702-1234").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-86752").Link("S180702-1234")_;_script infofile_;_ZIP::ssf7.xml_;_
'Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-86752").WebButton("Thoát Ra").Click @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager").Frame("mif-comp-ext-gen-top50-86752").WebButton("Thoát Ra")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("HPE Service Manager").Page("HPE Service Manager").Sync @@ hightlight id_;_Browser("HPE Service Manager").Page("HPE Service Manager")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("HPE Service Manager").CloseAllTabs
